# tasks file for percona-client
---
- import_tasks: repository.yml
  tags:
    - configuration
    - percona-client
    - percona-client-repository

- import_tasks: install.yml
  tags:
    - configuration
    - percona-client
    - percona-client-install

- import_tasks: configure.yml
  tags:
    - configuration
    - percona-client
    - percona-client-configure
